<a href="https://colab.research.google.com/github/thdgmltjd123/Assignment01/blob/master/%EC%86%A1%ED%9D%AC%EC%84%B1_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [ ]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [ ]:
#텐서는 numpy의 ndarray와 비슷하지만 GPU를 지원함.
#빈 행렬이 생성되는 순간 쓰레기 값으로 메모리를 차지함.
x = torch.empty(5, 3)
print(x)

tensor([[2.8228e-37, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.3235e-14, 1.8369e+28, 1.9433e-19],
        [3.3738e-12, 7.4086e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])


Construct a randomly initialized matrix:



In [ ]:
#uniform[0,1]
x = torch.rand(5, 3) # 5행 3열
print(x)

tensor([[0.4200, 0.7391, 0.5969],
        [0.9462, 0.2496, 0.1931],
        [0.0794, 0.9434, 0.1535],
        [0.3588, 0.6935, 0.7525],
        [0.9996, 0.1613, 0.6266]])


Construct a matrix filled zeros and of dtype long:



In [ ]:
#0으로 채워진 5행 3열 type = long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [ ]:
#직접 리스트를 넣어서 tensor생성 가능
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
#tensor.new_* --> 다른 텐서와 비슷한 타입 및 다른 사이즈를 갖고싶게 할 때
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
#tensor.*_like --> 다른 텐서와 같은 사이즈를 가지고 싶게 할 때.
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8823,  0.1557, -1.0671],
        [-1.4211, -1.2090,  1.1252],
        [-0.3064, -1.8779,  1.3333],
        [-0.6927, -0.6481,  0.8716],
        [-1.7270,  0.1516, -0.2913]])


Get its size:



In [ ]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [ ]:
#요소별 합
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3154,  0.2904, -0.3956],
        [-1.0884, -0.6885,  1.4374],
        [-0.1565, -1.8711,  1.6768],
        [-0.0061, -0.5758,  1.3929],
        [-1.5723,  1.1068,  0.0961]])


Addition: syntax 2



In [ ]:
print(torch.add(x, y))

tensor([[-0.3154,  0.2904, -0.3956],
        [-1.0884, -0.6885,  1.4374],
        [-0.1565, -1.8711,  1.6768],
        [-0.0061, -0.5758,  1.3929],
        [-1.5723,  1.1068,  0.0961]])


Addition: providing an output tensor as argument



In [ ]:
#빈 텐서를 반들고 텐서 x와 y를 더한 것을 빈 텐서에 저장
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3154,  0.2904, -0.3956],
        [-1.0884, -0.6885,  1.4374],
        [-0.1565, -1.8711,  1.6768],
        [-0.0061, -0.5758,  1.3929],
        [-1.5723,  1.1068,  0.0961]])


Addition: in-place



In [ ]:
#y.add_tensor --> y에 y+tensor를 저장
# adds x to y
y.add_(x)
print(y)

tensor([[-0.3154,  0.2904, -0.3956],
        [-1.0884, -0.6885,  1.4374],
        [-0.1565, -1.8711,  1.6768],
        [-0.0061, -0.5758,  1.3929],
        [-1.5723,  1.1068,  0.0961]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [ ]:
print(x)
print(x[:, 1])

tensor([[-0.8823,  0.1557, -1.0671],
        [-1.4211, -1.2090,  1.1252],
        [-0.3064, -1.8779,  1.3333],
        [-0.6927, -0.6481,  0.8716],
        [-1.7270,  0.1516, -0.2913]])
tensor([ 0.1557, -1.2090, -1.8779, -0.6481,  0.1516])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [ ]:
#numpy에서 reshape함수가 torch에서는 view함수이다.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6133])
-0.6132633686065674


**Slicing**

In [ ]:
x = torch.rand((4,5))

print("x = {}".format(x))
print("x[1] = {}".format(x[1]))
print("x[2,3] = {}".format(x[2,3]))
print("x[0, 1:4] = {}".format(x[0,1:4]))

x = tensor([[0.8868, 0.7318, 0.1991, 0.5965, 0.5367],
        [0.9230, 0.8502, 0.9421, 0.9882, 0.8131],
        [0.2674, 0.3784, 0.0508, 0.6449, 0.3960],
        [0.3251, 0.7350, 0.2559, 0.9271, 0.5113]])
x[1] = tensor([0.9230, 0.8502, 0.9421, 0.9882, 0.8131])
x[2,3] = 0.6448987126350403
x[0, 1:4] = tensor([0.7318, 0.1991, 0.5965])


**Multiplication**

1) Elementwise multiplication

In [ ]:
#원소곱 torch.mul
x = torch.tensor((1,2,3))
y = torch.tensor((4,5,6))
print(x)
print(y)
z = torch.mul(x,y) # same as x * y

print(z)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([ 4, 10, 18])


2) Dot product

In [ ]:
#점곱 inner product
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
print(x)
print(y)
z = torch.dot(x,y)
print(z)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(32)


3) Matrix multiplication

In [ ]:
#행렬 곱
x = torch.tensor([[1,1],[2,2],[3,3]]) # 3 x 2
y = torch.tensor([[6,5],[4,3]]) # 2 x 2

z = torch.matmul(x,y)
print("x.size() = {}".format(x.shape))
print("y.size() = {}".format(y.shape))
print("z.size() = {}".format(z.shape))

print("z = {}" .format(z))

x.size() = torch.Size([3, 2])
y.size() = torch.Size([2, 2])
z.size() = torch.Size([3, 2])
z = tensor([[10,  8],
        [20, 16],
        [30, 24]])


**Transpose**

'torch.transpose' returns a tensor that is a transposed version of input. 

The given dimension dim0 and dim1 are swapped.

In [ ]:
x = torch.rand((4,2))
print("x.size() = {}".format(x.shape))

y = x.T
print("y.size() = {}".format(y.shape))

a = torch.rand((1,2,3,4))
print("a.size() = {}".format(a.shape))

b = torch.transpose(a, dim0=1, dim1=2)
print("b.size() = {}".format(b.shape))

x.size() = torch.Size([4, 2])
y.size() = torch.Size([2, 4])
a.size() = torch.Size([1, 2, 3, 4])
b.size() = torch.Size([1, 3, 2, 4])


**Squeeze, Unsqueenze**

'torch.squeeze' returns a tensor with all the dimensions of input of size 1 removed.

'torch.unsqueeze' returns a tensor with a dimension of size one inserted at the specified position.

In [ ]:
#squeeze는 1인 차원을 없앤다. 위치정보를 입력해 특정 좌표의 1인 차원을 없앨 수 있다.
#unsqueeze는 해당하는 위치에 차원을 1 추가할 수 있다.
x = torch.rand(1,2,3,1,4)
y = torch.unsqueeze(x, dim=1)
print("x.size() = {}".format(x.shape))
print("y.size() = {}".format(y.shape))

z = torch.squeeze(x)
print("z.size() = {}".format(z.shape))


x.size() = torch.Size([1, 2, 3, 1, 4])
y.size() = torch.Size([1, 1, 2, 3, 1, 4])
z.size() = torch.Size([2, 3, 4])


**Cat**

Concatenates the given sequence of seq tensors in the given dimensions. 

In [ ]:
x = torch.rand(2,3)
print(x)
print("x.size() = {}".format(x.shape))

y = torch.cat((x,x), dim=0) #차원의 행이 더해진다
print(y)
print("y.size() = {}".format(y.shape))

z = torch.cat((x,x), dim=1) #차원의 열이 더해진다.
print(z)
print("z.size() = {}".format(z.shape))




tensor([[0.1494, 0.4297, 0.1121],
        [0.9947, 0.3101, 0.8516]])
x.size() = torch.Size([2, 3])
tensor([[0.1494, 0.4297, 0.1121],
        [0.9947, 0.3101, 0.8516],
        [0.1494, 0.4297, 0.1121],
        [0.9947, 0.3101, 0.8516]])
y.size() = torch.Size([4, 3])
tensor([[0.1494, 0.4297, 0.1121, 0.1494, 0.4297, 0.1121],
        [0.9947, 0.3101, 0.8516, 0.9947, 0.3101, 0.8516]])
z.size() = torch.Size([2, 6])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
#tensor는 numPy의 ndarray로 변환이 가능하고 그 반대도 가능하다.
#tensor와 ndarray는 같은 메모리 공간을 가진다.
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [ ]:
#ndarray-->tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!